### ISSUE TITLE
this example couldn'r run in Raspberry pi

### ISSUE THREAD

**Issue by wjfsh** [ControlEverythingCommunity/SHT30#1]
When I copied this codes and run it in python 2.7 of pi, it show as below:
pi@wjf:~/wjf/qt $ python SHT30_V1.py
Traceback (most recent call last):
  File "SHT30_V1.py", line 10, in <module>
    bus.write_i2c_block_data(0x44, 0x2C, [0x06])
IOError: [Errno 121] Remote I/O error
coul dyou help me to fix the bug, thanks.

**Comment by zaphod-42** [comment]
It sounds like you need to enable your I2C bus on the Pi, this article explains how to enable both I2C and SPI on your device

https://www.makeuseof.com/tag/enable-spi-i2c-raspberry-pi/
